<a href="https://colab.research.google.com/github/Dei-gratia/Machine-Learning-Projects/blob/main/Machine%20Learning%20%26%20Deep%20Learning%20Projects/Extreme_Learning_Machine_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
#import libraries
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score

In [23]:
#Define the EML model
class ELM(object):

    def __init__(self, inputSize, outputSize, hiddenSize):
        """
        Initialize weight and bias between input layer and hidden layer
        Parameters:
        inputSize: int
            The number of input layer dimensions or features in the training data
        outputSize: int
            The number of output layer dimensions
        hiddenSize: int
            The number of hidden layer dimensions
        """

        self.inputSize = inputSize
        self.outputSize = outputSize
        self.hiddenSize = hiddenSize

        # Initialize random weight with range [-0.5, 0.5]
        self.weight = np.matrix(np.random.uniform(-0.5, 0.5, (self.hiddenSize, self.inputSize)))

        # Initialize random bias with range [0, 1]
        self.bias = np.matrix(np.random.uniform(0, 1, (1, self.hiddenSize)))

        self.H = 0
        self.beta = 0

    def sigmoid(self, x):
        """
        Sigmoid activation function

        Parameters:
        x: array-like or matrix
            The value that the activation output will look for
        Returns:
            The results of activation using sigmoid function
        """
        return 1 / (1 + np.exp(-1 * x))

    def predict(self, X):
        """
        Predict the results of the training process using test data
        Parameters:
        X: array-like or matrix
            Test data that will be used to determine output using ELM
        Returns:
            Predicted results or outputs from test data
        """
        X = np.matrix(X)
        y = self.sigmoid((X * self.weight.T) + self.bias) * self.beta

        return y

    def fit(self, X, y):
        """
        Extreme Learning Machine training process
        Parameters:
        X: array-like or matrix
            Training data that contains the value of each feature
        y: array-like or matrix
            Training data that contains the value of the target (class)
        Returns:
            The results of the training process
        """

        X = np.matrix(X)
        y = np.matrix(y)

        # Calculate hidden layer output matrix (Hinit)
        self.H = (X * self.weight.T) + self.bias

        # Sigmoid activation function
        self.H = self.sigmoid(self.H)

        # Calculate the Moore-Penrose pseudoinverse matriks
        H_moore_penrose = np.linalg.inv(self.H.T * self.H) * self.H.T

        # Calculate the output weight matrix beta
        self.beta = H_moore_penrose * y

        return self.H * self.beta

In [24]:
#load dataset
dataset = datasets.make_classification(1000)
dataset

(array([[ 1.57735417, -0.72923805, -0.1117077 , ...,  0.23249841,
         -0.01078357, -1.19704836],
        [ 1.75194757,  0.95168014, -0.63917712, ...,  2.20579369,
         -0.8645969 ,  0.65180395],
        [ 0.96898127,  0.99754785, -1.26408176, ...,  0.32323693,
          0.73476775, -0.14833822],
        ...,
        [ 1.47540456, -0.43344015,  0.70237691, ..., -0.47799093,
         -0.95283135, -0.15174364],
        [-2.45543863,  1.66290772, -0.07951811, ...,  0.27903162,
          1.832583  , -0.84621041],
        [-1.22504597, -1.19533555,  0.22695892, ..., -0.76511737,
         -1.06261422,  0.76119672]]),
 array([1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
        0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
   

In [25]:
elm = ELM(dataset[0].shape[1], 2, 20)
elm

In [26]:
X_train, X_test, y_train, y_test = train_test_split(dataset[0], dataset[1], test_size=0.2, random_state=42)
print(X_train.shape, X_test.shape)

(800, 20) (200, 20)


In [27]:
elm.fit(X_train, y_train.reshape(-1,1))

matrix([[ 0.26236405],
        [ 0.26348446],
        [ 0.10672185],
        [ 0.72145416],
        [-0.57307331],
        [ 0.77684438],
        [ 0.94921341],
        [ 0.46618181],
        [-0.05217409],
        [ 0.08562597],
        [ 0.15558284],
        [ 0.24693221],
        [ 0.19081272],
        [ 0.74071364],
        [ 0.80633175],
        [ 0.33838621],
        [ 0.42530888],
        [ 0.25181435],
        [ 0.55465411],
        [ 0.42458063],
        [ 0.13989024],
        [ 0.81721374],
        [ 1.30329391],
        [ 0.26495507],
        [ 0.93894207],
        [ 0.68183486],
        [ 0.2548897 ],
        [ 0.96703884],
        [ 0.89334272],
        [ 0.69432823],
        [ 0.33158171],
        [ 0.73010973],
        [ 1.32358136],
        [ 0.88748932],
        [ 0.37288865],
        [ 0.9397984 ],
        [ 0.04631876],
        [-0.54074586],
        [-0.47552606],
        [ 0.91215474],
        [ 0.72405929],
        [ 0.67380445],
        [ 0.15462704],
        [ 0

In [38]:
#check accuracy score on training data
y_pred = elm.predict(X_train)
y_pred = (y_pred > 0.5).astype(int)
acc = accuracy_score(y_train, np.asarray(y_pred))
print("Accuracy on training data is: ", acc)

Accuracy on training data is:  0.9225


In [40]:
#check f1 score on training data
f1 = f1_score(y_train, np.asarray(y_pred))
print("Accuracy on training data is: ", f1)

Accuracy on training data is:  0.9217171717171717


In [41]:
#check accuracy score on test data
y_pred = elm.predict(X_test)
y_pred = (y_pred > 0.5).astype(int)
acc = accuracy_score(y_test, np.asarray(y_pred))
print("Accuracy on test data is: ", acc)

Accuracy on test data is:  0.935


In [42]:
#check f1 score on test data
f1 = f1_score(y_test, np.asarray(y_pred))
print("Accuracy on test data is: ", f1)

Accuracy on test data is:  0.9371980676328503
