<a href="https://colab.research.google.com/github/Dei-gratia/Machine-Learning-Projects/blob/main/ML%20course%20with%20Python/Building_Lasso_Regression_Model_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [109]:
#import the libraries
import numpy as np
import pandas as pd
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [124]:
#creating the Lasso Regression
class Lassor_Regression():
  #initialize the hyperparameters
  def __init__(self, learning_rate, no_of_iterations, lambda_param) -> None:
    self.learning_rate = learning_rate
    self.no_of_iterations = no_of_iterations
    self.lambda_param = lambda_param



  #fit the dataset to the model
  def fit(self, X, y):
    #initialise number of features and datapoints
    self.m, self.n = X.shape
    #initialize the bias and weights
    self.w = np.zeros(self.n)
    self.b = 0
    self.X = X
    self.y = y
    #implement gradient descent
    for i in range(self.no_of_iterations):
      self.update_weights()



  #update model weights and bias
  def update_weights(self):
    y_pred = self.predict(self.X)
    #gradient for weights
    dw = np.zeros(self.n)
    for i in range(self.n):
      if self.w[i] > 0:
        dw[i] = (-(2*(self.X[:,i]).dot(self.y - y_pred)) + self.lambda_param) / self.m
      else:
        dw[i] = (-(2*(self.X[:,i]).dot(self.y - y_pred)) - self.lambda_param) / self.m

    #gradient for bias
    db = -2 * np.sum(self.y - y_pred) / self.m

    #updating the weights and bias
    self.w = self.w - self.learning_rate * dw
    self.b = self.b - self.learning_rate * db


  #predict the target value
  def predict(self, X):
    print(X)
    print("-----------------------------------")
    print(self.w)
    print("-----------------------------------")
    print(self.b)
    print("-----------------------------------")
    return X.dot(self.w) + self.b


In [125]:
car_data = pd.read_csv("/content/car data.csv")
car_data.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

In [126]:
car_data.shape

(301, 9)

In [127]:
car_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       301 non-null    object 
 1   Year           301 non-null    int64  
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64  
 5   Fuel_Type      301 non-null    object 
 6   Seller_Type    301 non-null    object 
 7   Transmission   301 non-null    object 
 8   Owner          301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB


In [128]:
car_data.describe()

Year  Selling_Price  Present_Price     Kms_Driven       Owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296       7.628472   36947.205980    0.043189
std       2.891554       5.082812       8.644115   38886.883882    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [129]:
car_data["Car_Name"].value_counts()

city                        26
corolla altis               16
verna                       14
fortuner                    11
brio                        10
                            ..
Honda CB Trigger             1
Yamaha FZ S                  1
Bajaj Pulsar 135 LS          1
Activa 4g                    1
Bajaj Avenger Street 220     1
Name: Car_Name, Length: 98, dtype: int64

In [130]:
car_data.drop(columns="Car_Name", axis=1, inplace=True)

In [131]:
car_data = pd.get_dummies(data = car_data, drop_first=True)

In [133]:
#separate training and test data
X = car_data.drop(columns=["Selling_Price", "Year"], axis=1)
y = car_data["Selling_Price"]
print(X)
print(y)

     Present_Price  Kms_Driven  Owner  Fuel_Type_Diesel  Fuel_Type_Petrol  \
0             5.59       27000      0                 0                 1   
1             9.54       43000      0                 1                 0   
2             9.85        6900      0                 0                 1   
3             4.15        5200      0                 0                 1   
4             6.87       42450      0                 1                 0   
..             ...         ...    ...               ...               ...   
296          11.60       33988      0                 1                 0   
297           5.90       60000      0                 0                 1   
298          11.00       87934      0                 0                 1   
299          12.50        9000      0                 1                 0   
300           5.90        5464      0                 0                 1   

     Seller_Type_Individual  Transmission_Manual  
0                       

In [134]:
X = np.asarray(X)
y = np.asarray(y)
print(X)
print(y)

[[5.5900e+00 2.7000e+04 0.0000e+00 ... 1.0000e+00 0.0000e+00 1.0000e+00]
 [9.5400e+00 4.3000e+04 0.0000e+00 ... 0.0000e+00 0.0000e+00 1.0000e+00]
 [9.8500e+00 6.9000e+03 0.0000e+00 ... 1.0000e+00 0.0000e+00 1.0000e+00]
 ...
 [1.1000e+01 8.7934e+04 0.0000e+00 ... 1.0000e+00 0.0000e+00 1.0000e+00]
 [1.2500e+01 9.0000e+03 0.0000e+00 ... 0.0000e+00 0.0000e+00 1.0000e+00]
 [5.9000e+00 5.4640e+03 0.0000e+00 ... 1.0000e+00 0.0000e+00 1.0000e+00]]
[ 3.35  4.75  7.25  2.85  4.6   9.25  6.75  6.5   8.75  7.45  2.85  6.85
  7.5   6.1   2.25  7.75  7.25  7.75  3.25  2.65  2.85  4.9   4.4   2.5
  2.9   3.    4.15  6.    1.95  7.45  3.1   2.35  4.95  6.    5.5   2.95
  4.65  0.35  3.    2.25  5.85  2.55  1.95  5.5   1.25  7.5   2.65  1.05
  5.8   7.75 14.9  23.   18.   16.    2.75  3.6   4.5   4.75  4.1  19.99
  6.95  4.5  18.75 23.5  33.    4.75 19.75  9.25  4.35 14.25  3.95  4.5
  7.45  2.65  4.9   3.95  5.5   1.5   5.25 14.5  14.73  4.75 23.   12.5
  3.49  2.5  35.    5.9   3.45  4.75  3.8  11.25

In [135]:
#split the training and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=2)
print(X.shape, X_train.shape, X_test.shape)

(301, 7) (210, 7) (91, 7)


In [136]:
#train the model
model = Lassor_Regression(0.02, 1000, 200)
model.fit(X_train, y_train)

[[1.3600e+01 4.0126e+04 0.0000e+00 ... 1.0000e+00 0.0000e+00 1.0000e+00]
 [9.4000e+00 3.6198e+04 0.0000e+00 ... 1.0000e+00 0.0000e+00 0.0000e+00]
 [1.4700e+00 1.1000e+04 0.0000e+00 ... 1.0000e+00 1.0000e+00 1.0000e+00]
 ...
 [1.8610e+01 5.6001e+04 0.0000e+00 ... 1.0000e+00 0.0000e+00 1.0000e+00]
 [1.0790e+01 4.3000e+04 0.0000e+00 ... 0.0000e+00 0.0000e+00 1.0000e+00]
 [7.3000e-01 1.2000e+04 0.0000e+00 ... 1.0000e+00 1.0000e+00 1.0000e+00]]
-----------------------------------
[0. 0. 0. 0. 0. 0. 0.]
-----------------------------------
0
-----------------------------------
[[1.3600e+01 4.0126e+04 0.0000e+00 ... 1.0000e+00 0.0000e+00 1.0000e+00]
 [9.4000e+00 3.6198e+04 0.0000e+00 ... 1.0000e+00 0.0000e+00 0.0000e+00]
 [1.4700e+00 1.1000e+04 0.0000e+00 ... 1.0000e+00 1.0000e+00 1.0000e+00]
 ...
 [1.8610e+01 5.6001e+04 0.0000e+00 ... 1.0000e+00 0.0000e+00 1.0000e+00]
 [1.0790e+01 4.3000e+04 0.0000e+00 ... 0.0000e+00 0.0000e+00 1.0000e+00]
 [7.3000e-01 1.2000e+04 0.0000e+00 ... 1.0000e+00 1.0

/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


Streaming output truncated to the last 5000 lines.
 [1.8610e+01 5.6001e+04 0.0000e+00 ... 1.0000e+00 0.0000e+00 1.0000e+00]
 [1.0790e+01 4.3000e+04 0.0000e+00 ... 0.0000e+00 0.0000e+00 1.0000e+00]
 [7.3000e-01 1.2000e+04 0.0000e+00 ... 1.0000e+00 1.0000e+00 1.0000e+00]]
-----------------------------------
[nan nan nan nan nan nan nan]
-----------------------------------
nan
-----------------------------------
[[1.3600e+01 4.0126e+04 0.0000e+00 ... 1.0000e+00 0.0000e+00 1.0000e+00]
 [9.4000e+00 3.6198e+04 0.0000e+00 ... 1.0000e+00 0.0000e+00 0.0000e+00]
 [1.4700e+00 1.1000e+04 0.0000e+00 ... 1.0000e+00 1.0000e+00 1.0000e+00]
 ...
 [1.8610e+01 5.6001e+04 0.0000e+00 ... 1.0000e+00 0.0000e+00 1.0000e+00]
 [1.0790e+01 4.3000e+04 0.0000e+00 ... 0.0000e+00 0.0000e+00 1.0000e+00]
 [7.3000e-01 1.2000e+04 0.0000e+00 ... 1.0000e+00 1.0000e+00 1.0000e+00]]
-----------------------------------
[nan nan nan nan nan nan nan]
-----------------------------------
nan
-----------------------------------
[

In [122]:
training_data_prediction = model.predict(X_train)
print(training_data_prediction)

[[2.0140e+03 1.3600e+01 4.0126e+04 ... 1.0000e+00 0.0000e+00 1.0000e+00]
 [2.0130e+03 9.4000e+00 3.6198e+04 ... 1.0000e+00 0.0000e+00 0.0000e+00]
 [2.0170e+03 1.4700e+00 1.1000e+04 ... 1.0000e+00 1.0000e+00 1.0000e+00]
 ...
 [2.0130e+03 1.8610e+01 5.6001e+04 ... 1.0000e+00 0.0000e+00 1.0000e+00]
 [2.0160e+03 1.0790e+01 4.3000e+04 ... 0.0000e+00 0.0000e+00 1.0000e+00]
 [2.0130e+03 7.3000e-01 1.2000e+04 ... 1.0000e+00 1.0000e+00 1.0000e+00]]
-----------------------------------
[nan nan nan nan nan nan nan nan]
-----------------------------------
nan
-----------------------------------
[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan 

In [123]:
#check model accuracy on training data
training_data_prediction = model.predict(X_train)
accuracy_on_training_data = r2_score(y_train, training_data_prediction)
print("Accuracy on training data is: ", accuracy_on_training_data)

[[2.0140e+03 1.3600e+01 4.0126e+04 ... 1.0000e+00 0.0000e+00 1.0000e+00]
 [2.0130e+03 9.4000e+00 3.6198e+04 ... 1.0000e+00 0.0000e+00 0.0000e+00]
 [2.0170e+03 1.4700e+00 1.1000e+04 ... 1.0000e+00 1.0000e+00 1.0000e+00]
 ...
 [2.0130e+03 1.8610e+01 5.6001e+04 ... 1.0000e+00 0.0000e+00 1.0000e+00]
 [2.0160e+03 1.0790e+01 4.3000e+04 ... 0.0000e+00 0.0000e+00 1.0000e+00]
 [2.0130e+03 7.3000e-01 1.2000e+04 ... 1.0000e+00 1.0000e+00 1.0000e+00]]
-----------------------------------
[nan nan nan nan nan nan nan nan]
-----------------------------------
nan
-----------------------------------


ValueError: Input contains NaN.

In [ ]:
#check model accuracy on test data
test_data_prediction = model.predict(X_test)
accuracy_on_test_data = r2_score(y_test, test_data_prediction)
print("Accuracy on test data is: ", accuracy_on_test_data)